Unwrap incoming `Mono` parameters
salesforce/reactive-grpc pull request #301
Opened 2022-11-24 23:57 UTC by bsideup

It is uncommon to have methods accept `Mono` as a parameter. The fact that `ServerCalls` did `Mono.just` is also a good indicator. This change makes single-input methods look like `Mono<Response> foo(Request request)` instead of `Mono<Response> foo(Mono<Request> request)`.

It is backward compatible and will delegate to the `Mono` one (unless overridden, of course).

Closes #78 and #295

2022-11-24 23:59 UTC, bsideup commented
CLA signed 👍

2022-11-25 18:02 UTC, cbornet requested changes
Nice work !
Can you also add this  for RxJava ?

2022-11-25 20:42 UTC, bsideup commented
Hey @cbornet! Small world :) Done 👍

2022-11-26 00:51 UTC, cbornet commented
Yes, small world 😃 .
Could we also add some e2e tests in [Reactor EndToEndIntegrationTest](https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/EndToEndIntegrationTest.java#L143) and  [RxJava EndToEndIntegrationTest](https://github.com/salesforce/reactive-grpc/blob/master/rx3-java/rx3grpc-test/src/test/java/com/salesforce/rx3grpc/EndToEndIntegrationTest.java#L36). Maybe using the "Mono-unwrapped" client call ?

2022-11-26 16:36 UTC, bsideup commented
Hi @cbornet! Don't want to sound rude, but, before I do another turn, is there anything else you would want me to do for this PR to be accepted? I have an extremely limited time right now given my new role so it is pretty hard to iterate on things, I would rather prefer not to. Thanks!

2022-11-26 23:24 UTC, cbornet commented
Sorry, this came to my mind only after the first round. I sincerely apologize for this.
LGTM. Thanks a lot.

2022-11-26 23:27 UTC, cbornet approved these changes

2022-11-26 23:28 UTC, merged

2022-11-27 11:53 UTC, bsideup commented
@cbornet all good! Thanks for merging it.

It's been a while since the last release but there weren't any changes other than the dependency updates. Would it be possible to cut a release some time soon? Thanks in advance!

2022-11-28 21:46 UTC, cbornet commented
> It's been a while since the last release but there weren't any changes other than the dependency updates. Would it be possible to cut a release some time soon? 

@rmichela ?

2022-11-28 22:51 UTC, rmichela commented
I've lost my Maven Central access after leaving Salesforce. I'm trying to connect with @nikolay-pshenichny who took over my position as company representative.

2022-11-29 17:58 UTC, bsideup commented
Thank you @rmichela!

2023-04-13 00:58 UTC, bsideup commented
@rmichela thanks for the release! BTW it looks like this PR is missing from the release notes at https://github.com/salesforce/reactive-grpc/releases/tag/v1.2.4 . I don't mind as long as it is released, but I thought some might find the change very helpful :)

2023-04-13 01:27 UTC, rmichela commented
Will fix

2023-05-11 13:42 UTC, sheinbergon commented
@rmichela @bsideup Just out of curiosity - which  server were you testing this feature with? 
When testing wth Lognet gRPC start, I seem to be enocuntering `Ambiguous method <METHOD NAME> in service`, as it's detecting 2 methods with the same name (but diferent parameters). Is there a way I can disable this feature in the protoc plugin?